FROM nginx:latest

RUN apt-get update \
  && apt-get install -y gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY reload_nginx.sh /reload_nginx.sh
RUN chmod +x /reload_nginx.sh

COPY nginx.conf /tmp/nginx.conf

CMD ["/reload_nginx.sh"]